Type: AWS::ElasticBeanstalk::ConfigurationTemplate
Properties: 
  ApplicationName: "Ecommerce"
  Description: "String"
  EnvironmentId: "String"
  OptionSettings: 
    - ConfigurationOptionSetting
  PlatformArn: "String"
  SolutionStackName: "String"
  SourceConfiguration: 
    SourceConfiguration
